// Generated by KORE Compiler
// Direct HLSL codegen - SUPERCHARGED

cbuffer ShaderParams : register(b0)
{
    float time;
    float intensity;
};

Texture2D base_texture : register(t2);
SamplerState base_texture_sampler : register(s2);
Texture2D normal_map : register(t3);
SamplerState normal_map_sampler : register(s3);

struct VSInput
{
    float4 position : TEXCOORD0;
    float2 uv : TEXCOORD1;
};

struct PSOutput
{
    float4 color : SV_Target0;
};

PSOutput PSMain(VSInput input)
{
    float4 base_color = base_texture.Sample(base_texture_sampler, input.uv);
    float4 normal = normal_map.Sample(normal_map_sampler, input.uv);
    float4 wave = sin(((time * 2.000000) + (input.uv.x * 10.000000)));
    float4 pulse = cos((time * 3.000000));
    float2 offset = float2((wave * 0.010000), (pulse * 0.010000));
    float4 distorted_uv = (input.uv + offset);
    float4 distorted = base_texture.Sample(base_texture_sampler, distorted_uv);
    float3 rgb = distorted.rgb;
    float alpha = base_color.a;
    float brightness = dot(rgb, float3(0.299000, 0.587000, 0.114000));
    float4 saturated = clamp((brightness * intensity), 0.000000, 1.000000);
    float4 final_rgb = lerp(rgb, float3(saturated), 0.500000);
    float4 result = float4(final_rgb, alpha);
    PSOutput _result;
    _result.color = result;
    return _result;
}
