// Generated by KORE Compiler
// Direct HLSL codegen - SUPERCHARGED

cbuffer ShaderParams : register(b0)
{
    float time;
    float roughness;
    float metallic;
    float3 light_pos;
    float3 camera_pos;
};

Texture2D albedo_map : register(t3);
SamplerState albedo_map_sampler : register(s3);
Texture2D normal_map : register(t4);
SamplerState normal_map_sampler : register(s4);
Texture2D roughness_map : register(t5);
SamplerState roughness_map_sampler : register(s5);

struct VSInput
{
    float4 position : TEXCOORD0;
    float2 uv : TEXCOORD1;
    float3 normal : TEXCOORD2;
};

struct PSOutput
{
    float4 color : SV_Target0;
};

PSOutput PSMain(VSInput input)
{
    float3 albedo = albedo_map.Sample(albedo_map_sampler, input.uv).rgb;
    float3 normal_sample = normal_map.Sample(normal_map_sampler, input.uv).rgb;
    float roughness_sample = roughness_map.Sample(roughness_map_sampler, input.uv).r;
    float4 unpacked_normal = ((normal_sample * 2.000000) - 1.000000);
    float4 N = normalize(unpacked_normal);
    float3 world_pos = input.position.xyz;
    float4 V = normalize((camera_pos - world_pos));
    float4 L = normalize((light_pos - world_pos));
    float4 H = normalize((V + L));
    float NdotL = max(dot(N, L), 0.000000);
    float NdotV = max(dot(N, V), 0.000000);
    float NdotH = max(dot(N, H), 0.000000);
    float3 F0 = lerp(float3(0.040000), albedo, metallic);
    float fresnel_factor = pow((1.000000 - NdotV), 5.000000);
    float4 F = (F0 + (((float3(1.000000) - F0)) * fresnel_factor));
    float4 roughness_final = (roughness * roughness_sample);
    float4 specular = pow(NdotH, (((1.000000 - roughness_final)) * 128.000000));
    float4 diffuse = (albedo * NdotL);
    float4 spec = (F * specular);
    float4 ambient = (albedo * 0.030000);
    float4 final_color = ((ambient + diffuse) + spec);
    PSOutput _result;
    _result.color = float4(final_color, 1.000000);
    return _result;
}
