// Generated by KORE Compiler
// Direct HLSL codegen - SUPERCHARGED

Texture2D base_texture : register(t0);
SamplerState base_texture_sampler : register(s0);

struct VSInput
{
    float4 position : TEXCOORD0;
    float2 uv : TEXCOORD1;
};

struct PSOutput
{
    float4 color : SV_Target0;
};

PSOutput PSMain(VSInput input)
{
    float4 color = base_texture.Sample(base_texture_sampler, input.uv);
    PSOutput result;
    result.color = color;
    return result;
}
