// Generated by KORE Compiler
// Direct HLSL codegen - SUPERCHARGED

cbuffer ShaderParams : register(b0)
{
    float time;
    float4 wave_color;
};

Texture2D base_texture : register(t2);
SamplerState base_texture_sampler : register(s2);

struct VSInput
{
    float4 position : TEXCOORD0;
    float2 uv : TEXCOORD1;
};

struct PSOutput
{
    float4 color : SV_Target0;
};

PSOutput PSMain(VSInput input)
{
    float4 base = base_texture.Sample(base_texture_sampler, input.uv);
    float4 wave = sin(time);
    float4 result = (base * wave_color);
    PSOutput result;
    result.color = result;
    return result;
}
