; KORE Compiler Output - LLVM IR
; Generated by Project Ouroboros
; Compile with: clang output.ll kore_runtime.o -o output

target triple = "x86_64-pc-windows-msvc"

; External Runtime Functions
declare i8* @malloc(i64)
declare void @free(i8*)
declare i32 @printf(i8*, ...)
declare i32 @puts(i8*)

; Kore Runtime
declare void @kore_print_i64(i64)
declare void @kore_print_str(i64)
declare void @kore_println_str(i64)
declare i8* @kore_str_concat(i8*, i8*)
declare i64 @kore_array_new()
declare i64 @kore_array_push(i64, i64)
declare i64 @kore_array_pop(i64)
declare i64 @kore_array_get(i64, i64)
declare i64 @kore_array_len(i64)

; Kore Stdlib
declare i64 @kore_len(i64)
declare i64 @kore_str_len(i64)
declare i64 @kore_split(i64, i64)
declare i64 @kore_contains(i64, i64)
declare i64 @kore_ord(i64)
declare i64 @kore_chr(i64)
declare i64 @kore_to_int(i64)
declare i64 @kore_to_float(i64)
declare i64 @kore_to_string(i64)
declare i64 @kore_range(i64, i64)
declare i64 @kore_slice(i64, i64, i64)
declare i64 @kore_char_at(i64, i64)
declare i64 @kore_substring(i64, i64, i64)
declare i64 @kore_str_eq(i64, i64)
declare i64 @kore_append(i64, i64)
declare i64 @kore_add_op(i64, i64)
declare i64 @kore_sub_op(i64, i64)
declare i64 @kore_mul_op(i64, i64)
declare i64 @kore_div_op(i64, i64)
declare i64 @kore_rem_op(i64, i64)
declare i64 @kore_eq_op(i64, i64)
declare i64 @kore_neq_op(i64, i64)
declare i64 @kore_lt_op(i64, i64)
declare i64 @kore_le_op(i64, i64)
declare i64 @kore_gt_op(i64, i64)
declare i64 @kore_ge_op(i64, i64)
declare i64 @kore_is_truthy(i64)

; Direct Main Wrappers
declare i64 @args()
declare void @exit(i64)
declare i64 @read_file(i64)
declare i64 @write_file(i64, i64)
declare i64 @substring(i64, i64, i64)
declare i64 @replace(i64, i64, i64)
declare i64 @starts_with(i64, i64)
declare i64 @char_code_at(i64, i64)
declare i64 @char_from_code(i64)

; Built-in generic types (used as opaque pointers)
%Box = type { i64, i64 }
%Array = type { i64 }
%Option = type { i64, i8*, i8* }
%Vec = type { i64 }
%StringBuilder = type { i64 }
%Result = type { i64, i8*, i8* }
%HashMap = type { i64 }
%HashSet = type { i64 }
%Map = type { i64 }
%Set = type { i64 }

; Option/Box helpers
declare i64 @kore_some(i64)
declare i64 @kore_none()
declare i64 @kore_box(i64)
declare i64 @kore_unwrap(i64)
declare void @kore_panic(i64)

; Map/Variant helpers
declare i64 @kore_contains_key(i64, i64)
declare i64 @kore_join(i64, i64)
declare i64 @kore_peek(i64)
declare i64 @kore_peek_offset(i64, i64)
declare i64 @kore_variant_of(i64)
declare i64 @kore_variant_field(i64, i64)
declare i64 @Map_new()
declare void @kore_map_set(i64, i64, i64)
declare i64 @kore_map_get(i64, i64)
declare i64 @kore_create_token_payload(i64, i64)
declare i64 @kore_create_token_simple(i64)


define i64 @main_kore() {
  entry:
  %t0 = alloca i64
  store i64 -2216615441596374, i64* %t0
  %t1 = alloca i64
  store i64 -2216615441596316, i64* %t1
  %t2 = load i64, i64* %t0
  %t3 = load i64, i64* %t1
  %t4 = call i64 @kore_add_op(i64 %t2, i64 %t3)
  %t5 = alloca i64
  store i64 %t4, i64* %t5
  %t6 = load i64, i64* %t5
  %t7 = call i64 @kore_to_string(i64 %t6)
  call void @kore_println_str(i64 %t7)
  %t8 = getelementptr [6 x i8], [6 x i8]* @.str.0, i64 0, i64 0
  %t9 = ptrtoint i8* %t8 to i64
  %t10 = lshr i64 %t9, 3
  %t11 = or i64 %t10, 18444633011384221696
  %t12 = alloca i64
  store i64 %t11, i64* %t12
  %t13 = getelementptr [7 x i8], [7 x i8]* @.str.1, i64 0, i64 0
  %t14 = ptrtoint i8* %t13 to i64
  %t15 = lshr i64 %t14, 3
  %t16 = or i64 %t15, 18444633011384221696
  %t17 = alloca i64
  store i64 %t16, i64* %t17
  %t18 = load i64, i64* %t12
  %t19 = load i64, i64* %t17
  %t20 = call i64 @kore_str_concat(i64 %t18, i64 %t19)
  call void @kore_println_str(i64 %t20)
  %t21 = alloca i64
  store i64 -2181431069507583, i64* %t21
  %t22 = load i64, i64* %t21
  %t23 = call i64 @kore_is_truthy(i64 %t22)
  %t24 = icmp ne i64 %t23, 0
  br i1 %t24, label %then0, label %endif2
  then0:
  %t25 = getelementptr [13 x i8], [13 x i8]* @.str.2, i64 0, i64 0
  %t26 = ptrtoint i8* %t25 to i64
  %t27 = lshr i64 %t26, 3
  %t28 = or i64 %t27, 18444633011384221696
  call void @kore_println_str(i64 %t28)
  br label %endif2
  endif2:
  ret i64 0
}

; String Constants
@.str.0 = private unnamed_addr constant [6 x i8] c"Hello\00", align 8
@.str.1 = private unnamed_addr constant [7 x i8] c" World\00", align 8
@.str.2 = private unnamed_addr constant [13 x i8] c"Flag is true\00", align 8
