; KORE Compiler Output - LLVM IR (Untyped)
; Generated by Project Ouroboros
; Compile with: clang output.ll -o output


; External Runtime Functions
declare i8* @malloc(i64)
declare void @free(i8*)
declare i32 @printf(i8*, ...)
declare i32 @puts(i8*)

; Kore Runtime
declare void @kore_print_i64(i64)
declare void @kore_print_str(i8*)
declare void @kore_println_str(i8*)
declare i8* @kore_str_concat(i8*, i8*)
declare i64 @kore_array_new()
declare void @kore_array_push(i64, i64)
declare i64 @kore_array_get(i64, i64)
declare i64 @kore_array_len(i64)
declare i64 @kore_array_pop(i64)
declare i64 @kore_contains(i64, i64)
declare i64 @kore_contains_key(i64, i64)
declare void @kore_map_set(i64, i64, i64)
declare i64 @kore_map_get(i64, i64)
declare i64 @Map_new()
declare i64 @kore_split(i64, i64)
declare i64 @kore_join(i64, i64)
declare i64 @kore_str_len(i64)
declare i64 @kore_len(i64)
declare i64 @kore_str_eq(i64, i64)
declare i64 @kore_to_string(i64)
declare i64 @kore_to_int(i64)
declare i64 @kore_to_float(i64)
declare i64 @kore_range(i64, i64)
declare i64 @kore_ord(i64)
declare i64 @kore_chr(i64)
declare i64 @kore_char_at(i64, i64)
declare i64 @kore_char_code_at(i64, i64)
declare i64 @kore_file_read(i64)
declare i64 @kore_file_write(i64, i64)
declare i64 @kore_substring(i64, i64, i64)
declare void @kore_panic(i8*)
declare i64 @kore_variant_of(i64)
declare i64 @kore_variant_field(i64, i64)
declare i64 @kore_some(i64)
declare i64 @kore_none()
declare i64 @kore_alloc(i64)
declare i64 @kore_add_op(i64, i64)
declare i64 @kore_create_token_simple(i64)
declare i64 @kore_create_token_payload(i64, i64)
declare i64 @args()
declare void @exit(i64)
; Built-in Types
%Option = type { i64, i8*, i8* }
%Result = type { i64, i8*, i8* }


define i64 @main_kore() {
entry:
%t0 = alloca i64
store i64 42, i64* %t0
%t1 = alloca i64
store i64 100, i64* %t1
%t2 = load i64, i64* %t0
%t3 = load i64, i64* %t1
%t4 = call i64 @kore_add_op(i64 %t2, i64 %t3)
%t5 = alloca i64
store i64 %t4, i64* %t5
%t6 = load i64, i64* %t5
%t7 = call i64 @kore_to_string(i64 %t6)
%t8 = call i64 @kore_println_str(i64 %t7)
%t9 = getelementptr [8 x i8], [8 x i8]* @.str.0, i64 0, i64 0
%t10 = ptrtoint i8* %t9 to i64
%t11 = alloca i64
store i64 %t10, i64* %t11
%t12 = getelementptr [9 x i8], [9 x i8]* @.str.1, i64 0, i64 0
%t13 = ptrtoint i8* %t12 to i64
%t14 = alloca i64
store i64 %t13, i64* %t14
%t15 = load i64, i64* %t11
%t16 = load i64, i64* %t14
%t17 = call i64 @kore_add_op(i64 %t15, i64 %t16)
%t18 = call i64 @kore_println_str(i64 %t17)
%t19 = alloca i64
store i64 1, i64* %t19
%t20 = load i64, i64* %t19
%t21 = icmp ne i64 %t20, 0
br i1 %t21, label %then0, label %endif2
then0:
%t22 = getelementptr [15 x i8], [15 x i8]* @.str.2, i64 0, i64 0
%t23 = ptrtoint i8* %t22 to i64
%t24 = call i64 @kore_println_str(i64 %t23)
br label %endif2
endif2:
ret i64 0
}

; String Constants
@.str.0 = private unnamed_addr constant [8 x i8] c"\22Hello\22\00"
@.str.1 = private unnamed_addr constant [9 x i8] c"\22 World\22\00"
@.str.2 = private unnamed_addr constant [15 x i8] c"\22Flag is true\22\00"
