; KORE Compiler Output - LLVM IR
; Generated by Project Ouroboros
; Compile with: clang output.ll -o output


; External Runtime Functions
declare i8* @malloc(i64)
declare void @free(i8*)
declare i32 @printf(i8*, ...)
declare i32 @puts(i8*)
declare i64 @kore_is_truthy(i64)

; Kore Runtime
declare i64 @kore_print_i64(i64)
declare i64 @kore_print_str(i64)
declare i64 @kore_println_str(i64)
declare i64 @kore_str_concat(i64, i64)
declare i64 @kore_array_new()
declare i64 @kore_array_push(i64, i64)
declare i64 @kore_array_pop(i64)
declare i64 @kore_array_get(i64, i64)
declare i64 @kore_array_set(i64, i64, i64)
declare i64 @kore_array_len(i64)
declare i64 @Map_new()
declare i64 @kore_contains(i64, i64)
declare i64 @kore_contains_key(i64, i64)
declare void @kore_map_set(i64, i64, i64)
declare i64 @kore_map_get(i64, i64)
declare i64 @kore_split(i64, i64)
declare i64 @kore_join(i64, i64)
declare i64 @kore_str_starts_with(i64, i64)
declare i64 @kore_str_ends_with(i64, i64)
declare i64 @kore_str_replace(i64, i64, i64)
declare i64 @kore_str_len(i64)
declare i64 @kore_len(i64)
declare i64 @kore_str_eq(i64, i64)
declare i64 @kore_to_string(i64)
declare i64 @kore_to_int(i64)
declare i64 @kore_to_float(i64)
declare i64 @kore_range(i64, i64)
declare i64 @kore_ord(i64)
declare i64 @kore_chr(i64)
declare i64 @kore_char_at(i64, i64)
declare i64 @kore_char_code_at(i64, i64)
declare i64 @kore_file_read(i64)
declare i64 @kore_file_write(i64, i64)
declare i64 @read_file(i64)
declare i64 @write_file(i64, i64)
declare i64 @file_exists(i64)
declare i64 @kore_substring(i64, i64, i64)
declare void @kore_panic(i8*)
declare i64 @kore_variant_of(i64)
declare i64 @kore_variant_field(i64, i64)
declare i64 @kore_some(i64)
declare i64 @kore_none()
declare i64 @kore_alloc(i64)
declare i8* @kore_unbox_any_ptr(i64)
declare i64 @kore_box_ptr(i8*)
declare i64 @kore_add_op(i64, i64)
declare i64 @kore_sub_op(i64, i64)
declare i64 @kore_mul_op(i64, i64)
declare i64 @kore_div_op(i64, i64)
declare i64 @kore_rem_op(i64, i64)
declare i64 @kore_eq_op(i64, i64)
declare i64 @kore_neq_op(i64, i64)
declare i64 @kore_lt_op(i64, i64)
declare i64 @kore_le_op(i64, i64)
declare i64 @kore_gt_op(i64, i64)
declare i64 @kore_ge_op(i64, i64)
declare i64 @kore_create_token_simple(i64)
declare i64 @kore_create_token_payload(i64, i64)
declare i64 @args()
declare void @exit(i64)
declare i64 @kore_unwrap(i64)
; Built-in Types
%Option = type { i64, i8*, i8* }
%Result = type { i64, i8*, i8* }


define i64 @main_kore() {
entry:
ret i64 0
}

