; KORE Compiler Output - LLVM IR
; Generated by Project Ouroboros
; Compile with: clang output.ll -o output


; External Runtime Functions
declare i8* @malloc(i64)
declare void @free(i8*)
declare i32 @printf(i8*, ...)
declare i32 @puts(i8*)

; Kore Runtime
declare void @kore_print_i64(i64)
declare void @kore_print_str(i8*)
declare void @kore_println_str(i8*)
declare i8* @kore_str_concat(i8*, i8*)
declare i64 @kore_array_new()
declare void @kore_array_push(i64, i64)
declare i64 @kore_array_get(i64, i64)
declare i64 @kore_array_len(i64)

define i64 @main_kore() {
  entry:
  call void @kore_print_i64(i64 42)
  ret i64 0
}

