; KORE Compiler Output - LLVM IR (Untyped)
; Generated by Project Ouroboros
; Compile with: clang output.ll -o output


; External Runtime Functions
declare i8* @malloc(i64)
declare void @free(i8*)
declare i32 @printf(i8*, ...)
declare i32 @puts(i8*)

; Kore Runtime
declare void @kore_print_i64(i64)
declare void @kore_print_str(i8*)
declare void @kore_println_str(i8*)
declare i8* @kore_str_concat(i8*, i8*)
declare i64 @kore_array_new()
declare void @kore_array_push(i64, i64)
declare i64 @kore_array_get(i64, i64)
declare i64 @kore_array_len(i64)
declare i64 @kore_array_pop(i64)
declare i64 @kore_contains(i64, i64)
declare i64 @kore_contains_key(i64, i64)
declare void @kore_map_set(i64, i64, i64)
declare i64 @kore_map_get(i64, i64)
declare i64 @Map_new()
declare i64 @kore_split(i64, i64)
declare i64 @kore_join(i64, i64)
declare i64 @kore_str_len(i64)
declare i64 @kore_len(i64)
declare i64 @kore_str_eq(i64, i64)
declare i64 @kore_to_string(i64)
declare i64 @kore_to_int(i64)
declare i64 @kore_to_float(i64)
declare i64 @kore_range(i64, i64)
declare i64 @kore_ord(i64)
declare i64 @kore_chr(i64)
declare i64 @kore_char_at(i64, i64)
declare i64 @kore_char_code_at(i64, i64)
declare i64 @kore_file_read(i64)
declare i64 @kore_file_write(i64, i64)
declare i64 @kore_substring(i64, i64, i64)
declare void @kore_panic(i8*)
declare i64 @kore_variant_of(i64)
declare i64 @kore_variant_field(i64, i64)
declare i64 @kore_some(i64)
declare i64 @kore_none()
declare i64 @kore_alloc(i64)
declare i64 @kore_add_op(i64, i64)
declare i64 @kore_sub_op(i64, i64)
declare i64 @kore_mul_op(i64, i64)
declare i64 @kore_div_op(i64, i64)
declare i64 @kore_rem_op(i64, i64)
declare i64 @kore_eq_op(i64, i64)
declare i64 @kore_neq_op(i64, i64)
declare i64 @kore_lt_op(i64, i64)
declare i64 @kore_le_op(i64, i64)
declare i64 @kore_gt_op(i64, i64)
declare i64 @kore_ge_op(i64, i64)
declare i64 @kore_create_token_simple(i64)
declare i64 @kore_create_token_payload(i64, i64)
declare i64 @args()
declare void @exit(i64)
; Built-in Types
%Option = type { i64, i8*, i8* }
%Result = type { i64, i8*, i8* }


define i64 @main_kore() {
entry:
%t0 = getelementptr [20 x i8], [20 x i8]* @.str.0, i64 0, i64 0
%t1 = ptrtoint i8* %t0 to i64
%t2 = lshr i64 %t1, 3
%t3 = or i64 %t2, 0
%t4 = call i64 @kore_print_str(i64 %t3)
%t5 = icmp ne i64 0, 0
br i1 %t5, label %then0, label %endif2
then0:
%t6 = getelementptr [11 x i8], [11 x i8]* @.str.1, i64 0, i64 0
%t7 = ptrtoint i8* %t6 to i64
%t8 = lshr i64 %t7, 3
%t9 = or i64 %t8, 0
%t10 = alloca i64
store i64 %t9, i64* %t10
%t11 = load i64, i64* %t10
%t12 = call i64 @kore_print_str(i64 %t11)
br label %endif2
endif2:
%t13 = getelementptr [8 x i8], [8 x i8]* @.str.2, i64 0, i64 0
%t14 = ptrtoint i8* %t13 to i64
%t15 = lshr i64 %t14, 3
%t16 = or i64 %t15, 0
%t17 = alloca i64
store i64 %t16, i64* %t17
%t18 = getelementptr [8 x i8], [8 x i8]* @.str.3, i64 0, i64 0
%t19 = ptrtoint i8* %t18 to i64
%t20 = lshr i64 %t19, 3
%t21 = or i64 %t20, 0
%t22 = load i64, i64* %t17
%t23 = call i64 @kore_add_op(i64 %t21, i64 %t22)
%t24 = call i64 @kore_print_str(i64 %t23)
%t25 = getelementptr [9 x i8], [9 x i8]* @.str.4, i64 0, i64 0
%t26 = ptrtoint i8* %t25 to i64
%t27 = lshr i64 %t26, 3
%t28 = or i64 %t27, 0
store i64 %t28, i64* %t17
%t29 = getelementptr [8 x i8], [8 x i8]* @.str.5, i64 0, i64 0
%t30 = ptrtoint i8* %t29 to i64
%t31 = lshr i64 %t30, 3
%t32 = or i64 %t31, 0
%t33 = load i64, i64* %t17
%t34 = call i64 @kore_add_op(i64 %t32, i64 %t33)
%t35 = call i64 @kore_print_str(i64 %t34)
%t36 = call i64 @make_str()
%t37 = alloca i64
store i64 %t36, i64* %t37
%t38 = getelementptr [11 x i8], [11 x i8]* @.str.6, i64 0, i64 0
%t39 = ptrtoint i8* %t38 to i64
%t40 = lshr i64 %t39, 3
%t41 = or i64 %t40, 0
%t42 = load i64, i64* %t37
%t43 = call i64 @kore_add_op(i64 %t41, i64 %t42)
%t44 = call i64 @kore_print_str(i64 %t43)
ret i64 0
}

define i64 @make_str() {
entry:
%t0 = getelementptr [14 x i8], [14 x i8]* @.str.7, i64 0, i64 0
%t1 = ptrtoint i8* %t0 to i64
%t2 = lshr i64 %t1, 3
%t3 = or i64 %t2, 0
%t4 = alloca i64
store i64 %t3, i64* %t4
%t5 = load i64, i64* %t4
ret i64 %t5
}

; String Constants
@.str.0 = private unnamed_addr constant [20 x i8] c"\22=== Leak Test ===\22\00", align 8
@.str.1 = private unnamed_addr constant [11 x i8] c"\22ScopeVar\22\00", align 8
@.str.2 = private unnamed_addr constant [8 x i8] c"\22First\22\00", align 8
@.str.3 = private unnamed_addr constant [8 x i8] c"\22x is \22\00", align 8
@.str.4 = private unnamed_addr constant [9 x i8] c"\22Second\22\00", align 8
@.str.5 = private unnamed_addr constant [8 x i8] c"\22x is \22\00", align 8
@.str.6 = private unnamed_addr constant [11 x i8] c"\22Result: \22\00", align 8
@.str.7 = private unnamed_addr constant [14 x i8] c"\22LocalString\22\00", align 8
