// Generated by KORE Compiler (Project Ouroboros)
// Do not edit - regenerate from .kr source

#![allow(unused_variables)]
#![allow(unused_mut)]
#![allow(dead_code)]
#![allow(unused_parens)]

use std::collections::HashMap;
use std::rc::Rc;
use std::cell::RefCell;

#[derive(Debug, Clone)]
struct PBRParams {
    pub normal_strength: f64,
    pub roughness_base: f64,
    pub metallic_base: f64,
    pub ao_intensity: f64,
}

fn lerp(a: f64, b: f64, t: f64) -> f64  {
    return (a + ((b - a) * t));
}

fn clamp(value: f64, min: f64, max: f64) -> f64  {
    if (value < min) {
        return min;
    }
    if (value > max) {
        return max;
    }
    return value;
}

fn compute_roughness(base: f64, variation: f64, noise: f64) -> f64  {
    let adjusted = (base + (variation * noise));
    return clamp(adjusted, 0.0, 1.0);
}

fn main()  {
    let params = PBRParams { normal_strength: 1.0, roughness_base: 0.5, metallic_base: 0.0, ao_intensity: 1.0 };
    let roughness = compute_roughness(params.roughness_base, 0.2, 0.75);
    println!("{} {}", "Roughness:".to_string(), roughness);
}

